### ISSUE TITLE
New event: MatrixJsonRoomTopicEvent

### ISSUE THREAD

**Issue by MrCustomizer** [kamax-io/matrix-java-sdk#41]
I suggest adding a new event which implements `MatrixJsonEvent` with the name `MatrixJsonRoomTopicEvent`. This event should be a represantation of a timeline event of a room with the type `m.room.topic`.

**Comment by maxidor** [comment]
agreed and already working on it with its brother `MatrixJsonRoomNameEvent` ;)

**Comment by MrCustomizer** [comment]
I would like to have an event for room aliases, too. Something like `MatrixJsonRoomAliasesEvent`.

**Comment by maxidor** [comment]
Added in bcdd45b

**Comment by MrCustomizer** [comment]
All three event types are added to Palaver now and they are working fine. Thanks.
