### ISSUE TITLE
New object for unread notifications (from sync data)

### ISSUE THREAD

**Issue by MrCustomizer** [kamax-io/matrix-java-sdk#46]
The object `JoinedRoom` in `SyncData` needs a new object to read the unread notifications and highlights. Relevant part of the spec: https://matrix.org/docs/spec/client_server/r0.3.0.html#get-matrix-client-r0-sync

**Comment by maxidor** [comment]
@MrCustomizer `0.0.12-1-ge6710b2` now has `getUnreadNotifications()` on a `JoinedRoom` from `SyncData`. Let me know if it works as expected.

**Comment by MrCustomizer** [comment]
That works very nicely, thanks! One question, though: Why are the counters of type Long? It's described as Integer in the spec.

**Comment by maxidor** [comment]
@MrCustomizer: JSON Integer = Java Long

**Comment by MrCustomizer** [comment]
I see. Then everything is fine!
