### ISSUE TITLE
Support for membership parameter of MatrixJsonRoomMembershipEvent

### ISSUE THREAD

**Issue by MrCustomizer** [kamax-io/matrix-java-sdk#47]
`MatrixJsonRoomMembershipEvent` has to be extended, so that it is possible to query the membership parameter of the JSON object. According to the spec it can contain the following values: "invite", "join", "knock", "leave" and "ban".

**Comment by maxidor** [comment]
It's [already available](https://github.com/kamax-io/matrix-java-sdk/blob/master/src/main/java/io/kamax/matrix/json/event/MatrixJsonRoomMembershipEvent.java#L46), unless I missunderstood what you're after.

**Comment by MrCustomizer** [comment]
Oops, you're right. Thanks for pointing that out.
